GET http://localhost:8080/hello
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmb28iLCJleHAiOjE2MDc2NDcxNDMsImlhdCI6MTYwNzYxMTE0M30.BYhf0AW_TS--NeESdaQ-LOHr7EKjlsi7Du8q9NQTdpk

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "foo",
  "password": "foo"
}

###
