GET http://localhost:8080/hello
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmb28iLCJleHAiOjE2MDc2NDY4MTQsImlhdCI6MTYwNzYxMDgxNH0.q-IowvLTC6YkGV4qBggdy9BuV8fVDT2Gdg3_-g-XrT0

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "foo",
  "password": "foo"
}

###
